# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be90e35ac4303a8519fda52a8e0ffc74d1b980198096a01c219f82a6893b4d696d3a7208d78c335ad21f00d9db4bd995ae08951c8966c028a160fdaf64ebf86e

test:
  secret_key_base: 2a97e27d62211134bcba2ca223eae813eccf238d0d46c37fd302ab190bf534246f389f398f38a1227503e5bf563d274123c4d12d69526f23350dc775fc1c9122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
